apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-fancylink
spec:
  acme:
    email: gmartins@fancywhale.ca
    privateKeySecretRef:
      name: issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        azureDNS:
          clientID: 50c8bea7-3db8-4a36-9d38-6d507f3526dd
          clientSecretSecretRef:
            key: client-secret
            name: azuredns-config-fancylink
          environment: AzurePublicCloud
          hostedZoneName: fancywhale.link
          resourceGroupName: fancywhale
          subscriptionID: e1ae4488-8ac8-4d66-a72d-fe07907d1571
          tenantID: 2952ab0d-7932-43dd-8089-0a4256779fb1
