apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: immich
  namespace: immich
spec:
  interval: 1m
  url: https://github.com/immich-app/immich-charts
  ref:
    branch: main