apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: immich
spec:
  interval: 1m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: immich
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: immich
      interval: 1m
  values:
    auth:
      username: postgresql
      database: immich
      existingSecret: postgresql-secret
      secretKeys:
        replicationPasswordKey: replicationPassword
        userPasswordKey: userPassword
        adminPasswordKey: adminPassword
    primary:
      persistence:
        enabled: true
        existingClaim: postgresql-immich