apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  releaseName: immich
  interval: 5m
  chart:
    spec:
      chart: charts/apps/immich
      sourceRef:
        kind: GitRepository
        name: immich
        namespace: immich
      interval: 1m
  values:
    common_env:
      OAUTH_ENABLED: "true"
      OAUTH_ISSUER_URL: "https://authentik.fancywhale.ca/application/o/immich/.well-known/openid-configuration"
      OAUTH_CLIENT_ID: "afd22fcf1016ae1528658967382a231b1d7d47b8"
      OAUTH_CLIENT_SECRET:
        valueFrom:
          secretKeyRef:
            name: immich-secret
            key: oauth_client_secret
      OAUTH_BUTTON_TEXT: "Authentik SSO"
      JWT_SECRET:
        valueFrom:
          secretKeyRef:
            name: immich-secret
            key: jwt_secret
      DB_PASSWORD: 
        valueFrom:
          secretKeyRef:
            name: postgres-auth
            key: password
    postgresql:
      enabled: true
      global:
        postgresql:
          auth:
            username: immich
            database: immich
            existingSecret: postgres-auth
    persistence:
      library:
        enabled: true
        type: nfs
        server: 10.88.108.188
        path: /volume1/nextcloud
        mountPath: /usr/src/app/upload
        readOnly: false
        accessMode: ReadWriteMany
        size: 500Gi
        retain: false
    redis:
      enabled: true
      auth:
        enabled: false
    ingress:
      main:
        ingressClassName: nginx
        annotations: 
          cert-manager.io/cluster-issuer: letsencrypt
          nginx.ingress.kubernetes.io/proxy-body-size: 1G
          nginx.org/proxy-body-size: 1G
          nginx.org/client-max-body-size: "1G"
          nginx.ingress.kubernetes.io/client-max-body-size: 1G
          nginx.org/proxy-connect-timeout: 3600s
          nginx.org/proxy-read-timeout: 3600s
          nginx.org/proxy-send-timeout: 3600s
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        enabled: true
        primary: true
        hosts:
        - host: immich.fancywhale.ca
          paths:
          - path: "/"
        tls:
        - hosts:
          - immich.fancywhale.ca
          secretName: immich-fancywhale-ca-tls
    server:
      image:
        tag: &image-tag v1.49.0
    microservice:
      image:
        tag: *image-tag
    machine_learning:
      command: [ "python", "src/main.py" ]
      image:
        tag: *image-tag
    web:
      image:
        tag: *image-tag
    proxy:
      image:
        tag: *image-tag