apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  releaseName: immich
  interval: 5m
  chart:
    spec:
      chart: charts/apps/immich
      sourceRef:
        kind: GitRepository
        name: immich
        namespace: immich
      interval: 1m
  values:
    common_env:
      DB_PASSWORD: 
        valueFrom:
          secretKeyRef:
            name: postgres-auth
            key: password
    postgresql:
      enabled: true
      global:
        postgresql:
          auth:
            username: immich
            database: immich
            existingSecret: postgres-auth
    persistence:
      library:
        enabled: true
        type: nfs
        server: 10.88.108.188
        path: /volume1/nextcloud
        mountPath: /usr/src/app/upload
        readOnly: false
        accessMode: ReadWriteMany
        size: 500Gi
        retain: false
    redis:
      enabled: true
      auth:
        enabled: false
    ingress:
      main:
        ingressClassName: nginx
        annotations: 
          cert-manager.io/cluster-issuer: letsencrypt
        enabled: true
        primary: true
        hosts:
        - host: immich.fancywhale.ca
          paths:
          - path: "/"
        tls:
        - hosts:
          - immich.fancywhale.ca
          secretName: immich-fancywhale-ca-tls

      