apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: fancylanding-chart
  namespace: fancywhale
spec:
  interval: 1m
  url: https://github.com/gcarrarom/fancylanding-chart
  ref:
    branch: main
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: "."
      version: '0.1.0'
      appVersion: "0.0.7"
      sourceRef:
        kind: GitRepository
        name: fancylanding-chart
        namespace: fancywhale
      interval: 1m
  values:
    image:
      repo: gcarrarom/landing
