---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: pihole
      interval: 1m
  values:
    serviceDns:
      type: LoadBalancer
    serviceDhcp:
      type: LoadBalancer
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
      - pihole.fancywhale.ca
      tls:
        - hosts:
          - pihole.fancywhale.ca
          secretName: pihole-fancywhale-ca-tls
    persistentVolumeClaim:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: "500Mi"
      storageClass: nfs-client
    admin:
      existingSecret: pihole-admin
      passwordKey: password
    DNS1: "1.1.1.1"
    DNS2: "1.0.0.1"