apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: fancywhale
spec:
  interval: 1m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: fancywhale
spec:
  interval: 5m
  chart:
    spec:
      chart: mariadb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: fancywhale
      interval: 1m
  values:
    auth:
      existingSecret: maria-secret
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: link
  namespace: fancywhale
spec:
  interval: 5m
  chart:
    spec:
      chart: main
      sourceRef:
        kind: GitRepository
        name: fancychart
        namespace: fancywhale
      interval: 1m
  values:
    image:
      repo: shlinkio/shlink # {"$imagepolicy": "flux-system:fancylink:name"}
      tag: 3.4.0 # {"$imagepolicy": "flux-system:fancylink:tag"}
    port: 8080
    env:
      DEFAULT_DOMAIN: fancywhale.link
      IS_HTTPS_ENABLED: "true"
      GEOLITE_LICENSE_KEY: CFcARleAPNQaUKr2
      DB_DRIVER: maria
      DB_USER: root
      DB_HOST: mariadb
    envFromSecret:
    - name: DB_PASSWORD
      secretName: maria-secret
      key: mariadb-root-password
    url: fancywhale.link
    clusterissuer: letsencrypt-fancylink
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: link-admin
  namespace: fancywhale
spec:
  interval: 5m
  chart:
    spec:
      chart: main
      sourceRef:
        kind: GitRepository
        name: fancychart
        namespace: fancywhale
      interval: 1m
  values:
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/auth-url: |-
          http://authentik.identity.svc.cluster.local/outpost.goauthentik.io/auth/nginx
        nginx.ingress.kubernetes.io/auth-signin: |-
          https://admin.fancywhale.link/outpost.goauthentik.io/start?rd=$escaped_request_uri
        nginx.ingress.kubernetes.io/auth-response-headers: |-
          Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
        nginx.ingress.kubernetes.io/auth-snippet: |
          proxy_set_header X-Forwarded-Host $http_host;
    image:
      repo: shlinkio/shlink-web-client # {"$imagepolicy": "flux-system:fancylink-admin:name"}
      tag: 3.8.2 # {"$imagepolicy": "flux-system:fancylink-admin:tag"}
    envFromSecret:
    - name: SHLINK_SERVER_API_KEY
      secretName: link-api-key
      key: api_key
    env:
      SHLINK_SERVER_URL: https://fancywhale.link
      SHLINK_SERVER_NAME: "Fancy Links"
    port: 80
    url: admin.fancywhale.link
    clusterissuer: letsencrypt-fancylink
