apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fancylanding
  namespace: fancywhale
spec:
  releaseName: fancylanding
  interval: 5m
  chart:
    spec:
      chart: main
      sourceRef:
        kind: GitRepository
        name: fancychart
        namespace: fancywhale
      interval: 1m
  values:
    image:
      repo: gcarrarom/landing
      tag: 0.2.1
    url: fancywhale.ca