apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: kuma
  namespace: flux-system
spec:
  image: louislam/uptime-kuma
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: kuma
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: kuma
  policy:
    semver:
      range: ">=1.21.0"