apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuma-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-static
  volumeMode: Filesystem
  volumeName: kuma-data