apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: changedetection
  namespace: changedetection
spec:
  interval: 5m
  chart:
    spec:
      chart: main
      sourceRef:
        kind: GitRepository
        name: fancychart
        namespace: changedetection
      interval: 1m
  values:
    image:
      repo: dgtlmoon/changedetection.io
      tag: 0.39.22.1
    port: 5000
