apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: fancywhale
spec:
  interval: 1m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: vaultwarden
spec:
  interval: 5m
  chart:
    spec:
      chart: mariadb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: fancywhale
      interval: 1m
  values:
    auth:
      existingSecret: maria-secret
    primary:
      persistence:
        enabled: true
        existingClaim: mariadb-vaultwarden
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vaultwarden
spec:
  interval: 5m
  chart:
    spec:
      chart: main
      sourceRef:
        kind: GitRepository
        name: fancychart
        namespace: fancywhale
      interval: 1m
  values:
    image:
      repo: vaultwarden/server
      tag: 1.27.0
    port: 80
    recreate: true
    volumes:
    - name: vaultwarden-data
      path: /data
    env:
      RUST_BACKTRACE: 1
      ORG_EVENTS_ENABLED: true
    envFromSecret:
    - secretName: vaultwarden-secrets
      secretRef: true
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/proxy-body-size: 1G
        nginx.org/proxy-body-size: 1G
        nginx.org/client-max-body-size: "1G"
        nginx.ingress.kubernetes.io/client-max-body-size: 1G
        nginx.org/proxy-connect-timeout: 3600s
        nginx.org/proxy-read-timeout: 3600s
        nginx.org/proxy-send-timeout: 3600s
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      