apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: 2fancy
  namespace: 2fancy
spec:
  interval: 5m
  chart:
    spec:
      chart: main
      sourceRef:
        kind: GitRepository
        name: fancychart
        namespace: 2fancy
      interval: 1m
  values:
    image:
      repo: gcarrarom/2fancy
      tag: 1
    port: 80
    url: 2fancy.ca
    clusterissuer: letsencrypt-2fancy

